[build]
  publish = "dist"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18"
  VITE_DOMAIN = "https://s-e-t-club.ru"
  NPM_FLAGS = "--production=false"

# Error pages
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 200

# React Router support
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirect www to non-www
[[redirects]]
  from = "https://www.s-e-t-club.ru/*"
  to = "https://s-e-t-club.ru/:splat"
  status = 301
  force = true

# Redirect HTTP to HTTPS
[[redirects]]
  from = "http://s-e-t-club.ru/*"
  to = "https://s-e-t-club.ru/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.s-e-t-club.ru/*"
  to = "https://s-e-t-club.ru/:splat"
  status = 301
  force = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# JavaScript files MIME type fix
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

# ES modules MIME type fix
[[headers]]
  for = "*.mjs"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

# TypeScript compiled files
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.gif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"